### ISSUE TITLE
Dependencies being downgraded in pull requests

### ISSUE THREAD

**Issue by greg-1-anderson** [dependencies-io/php#18]
In https://github.com/greg-1-anderson/gk-8/pull/29, dependencies.io downgraded one dependency, drupal/core, from the latest version to an earlier version. I suspect that the reason may be due to the [php version used to run composer update](https://github.com/greg-1-anderson/gk-8/pull/29/files#diff-1da2c7edc898c70e5a79a9997c98ceccL1552).  I tried [forcing a minimum in composer.json](https://github.com/greg-1-anderson/gk-8/blob/8d43efd9616c80bc4c3e0c2c98db289e4d937a9d/composer.json#L13), but that did not have any effect, so I'm not completely sure of the cause. In theory, the `composer update` should have failed if done with an earlier version of php.

**Comment by davegaeddert** [comment]
@greg-1-anderson thanks for the report. That does look a little strange. I double-checked the PHP version in the container and it should be well above 7.0.8:
![image](https://user-images.githubusercontent.com/649496/39434954-b6fb30e6-4c5f-11e8-9602-37b5c6f95cc7.png)

I ran it with:
```yml
version: 2
dependencies:
- type: php
  path: /
  settings:
    composer_options: "--ignore-platform-reqs"
  manifest_updates:
    filters:
    - name: ".*"
      versions: "L.Y.Y"
```
and it looks like that does give a better update (https://github.com/davegaeddert/gk-8/pull/2), so it must be some kind of platform requirement somewhere. I'm having a hard time tracking it down exactly where it stemmed from though. Any thoughts on what it might be? I guess my first suggestion would be that you run it with `--ignore-platform-reqs`, as our Docker image currently doesn't have all of the [platform packages](https://getcomposer.org/doc/01-basic-usage.md#platform-packages) installed.
